### ISSUE TITLE
Blocking Call(sh): Timeout

### ISSUE THREAD

**Issue by pwaller** [DisposaBoy/GoSublime#590]
I have:

```json
{
    "fmt_cmd": ["goimports"]
}
```

`goimports` takes 1.032s to run.

I see in the console:

```
** 2015-01-09 11:46:11.587429 **:
GoSublime
cannot fmt file. error: `Blocking Call(sh): Timeout'
--------------------------------

Writing file /home/pwaller/.../foo.go with encoding UTF-8
```

**Comment by shurcooL** [comment]
I ran into this issue too.

Sometimes `goimports` will take a while to run (it depends on some factors, like total number of Go packages in GOPATH, whether new imports need to be added, etc.).

As a result, with the default timeout of 1 second, sometimes (but not other times), when I Cmd+S and expect the file to be `gofmt`ed, that is not the case.

I rely on Cmd+S to always format my Go code, and these arbitrary potential failures are not okay - it can mean I can accidentally commit unformatted Go code without noticing.

I can increase `ipc_timeout` to 2 seconds or 10 seconds or 60 seconds to avoid this, but that isn't optimal. If `goimports` (or whatever fmt_cmd I have set) takes 61 seconds, I don't want it to (largely invisibly) not do anything.

Additionally, for all other users that don't realize this potential pitfall and use default settings (which results in a timeout of 1 second), they have a non-zero probability of running into this too and therefore committing unformatted Go code, etc.

I think the fmt_cmd process should be an exception and executed without any timeout. If it takes too long to run, the user should fix the problem (by using a faster `gofmt`, or removing many packages from their GOPATH, or make a contribution to `goimports` project to make it faster, etc.). There should be a 100% guarantee that if you press Cmd+S that it will eventually format your code, without a chance of it deciding not to (because of timeout).

**Comment by hermanschaaf** [comment]
I also ran into this issue, and was wondering why sometimes my files weren't being formatted. I agree with @shurcooL that it should never fail, and that users should rather seek to make the process faster if it is taking too long.

**Comment by pararthshah** [comment]
Also ran into this. Agree with @shurcooL (your fix worked for me - thanks!)

**Comment by slimsag** [comment]
I've been running into this too lately :( @shurcooL's fix worked for me.

I agree it's not good that goimports takes so long to execute.. but having it not run at all is even worse! I look really silly committing unformatted code :grin:

**Comment by DisposaBoy** [comment]
If anyone has any suggestion on a way GS can work better here, please feel free to share. As things stand, due to limitations in ST, I can't fmt the file without it being a blocking call. This means that for the entirely of the call to margo the ST ui is frozen. I think `goimports` should simply be fixed. IIRC there was talk of possibly running daemon so it could cache stuff, but I don't use `goimports` and haven't kept up with the discussions. If more support is required from me and `goimports` provides a package (not binary) that will do the caching, then I'm open to including it as part of the margo binary the same way `gocode` is.

**Comment by shurcooL** [comment]
> If anyone has any suggestion on a way GS can work better here, please feel free to share.

My suggestion is this. When running the on-save formatting command (configured as either `gofmt` or `goimports`, run it without a timeout (or with a really long timeout, like 30 seconds or longer).

If `goimports` is slow, users should deal with that by making it faster (e.g., by contributing performance improvements to the tool, or by reducing number of unneeded Go packages they have in their Go workspace, or by switching to `gofmt`).

> As things stand, due to limitations in ST, I can't fmt the file without it being a blocking call. This means that for the entirely of the call to margo the ST ui is frozen.

That's fine by mine. It's what I expect, I press save, and the format tool runs until it completes, without timing out.

**Comment by DisposaBoy** [comment]
I've chosen to improve the documentation: https://github.com/DisposaBoy/GoSublime/commit/43858c654c41a233d0fff2bd7922ab587b4ebaa6

If it can be made clearer, feel free to make suggestions.


I can't make the timeout infinite - that's crazy. If it wasn't clear: this setting isn't something special for `gofmt`, it applies to every blocking ipc call including ones triggered automatically by Sublime Text e.g. `completion` - and I don't plan to add any more special cases for `goimports` unless it is to be supported officially.

I decided not to increase it because this interacts badly with other plugins and I've seen Sublime Text crash when frozen for a little while before.

I also considered making the error more noisy, but decided against it because `fmt` fails all the time, e.g. on syntax errors and it'd be very annoying if it's always in your face.

**Comment by shurcooL** [comment]
> I can't make the timeout infinite - that's crazy. If it wasn't clear: this setting isn't something special for gofmt, it applies to every blocking ipc call including ones triggered automatically by Sublime Text e.g. completion

Yeah, that wouldn't be appropriate. I meant it should be "infinite" (effectively) only for the command that formats code on save, because it's very important. Not other commands like getting autocompletion.

> I don't plan to add any more special cases for `goimports` unless it is to be supported officially.

What do you mean by officially? It started off as Brad Fitzpatrick's personal project on github.com/bradfitz/goimports, but has since moved to Go external standard library at `golang.org/x/tools/cmd/goimports`. Are you saying it's only official if it's moved into internal standard library, like `cmd/goimports`?

> I also considered making the error more noisy, but decided against it because fmt fails all the time, e.g. on syntax errors and it'd be very annoying if it's always in your face.

Is it possible to tell the difference when the command fails (because of invalid Go code), or when it's killed by the ipc_timeout setting? If so, you could consider displaying a message like "WARNING: You pressed saved and thought your code would be `gofmt`ed, but it wasn't because 1 second passed and the formatting tool hasn't finished yet!". I think even something as annoying as that would be better than silently not formatting one's code on timeout. But it's because I think it's absolutely unacceptable for a Go code editor to silently not gofmt code on save under certain situations.

> If it can be made clearer, feel free to make suggestions.

Looks like a good start, thanks for doing that!

I think it's unfortunate that the default GoImports behavior can't be optimal, but I suppose it's fair to require people to configure a higher ipc_timeout when they configure goimports as their gofmt tool.

**Comment by DisposaBoy** [comment]
https://github.com/DisposaBoy/GoSublime/commit/dd981730f13b3a146d256271ce94bad557155802 adds the timeout value to the bcall error message well as mentioning the `ipc_timeout` setting.

https://github.com/DisposaBoy/GoSublime/commit/668409c1a669b3b339cd1fd548b36e5365a0066c shows a popup if fmt fails for any reason.

@shurcooL 

> What do you mean by officially? 

By officially, I mean officially as part of GoSublime/MarGo.


> Is it possible to tell the difference when the command fails (because of invalid Go code), or when it's killed by the ipc_timeout setting?

It's possible to detect the timeout but I don't think it helps, because the fmt can fail for other reasons as well. It's best to simply be aware that it can fail at all.

**Comment by shurcooL** [comment]
Ok, thanks. From my perspective, I consider this issue being resolved and could be closed. Thanks for doing that work!
