### ISSUE TITLE
MarGo build failed (OS X Yosemite 10.10.1)

### ISSUE THREAD

**Issue by ChristianSiegert** [DisposaBoy/GoSublime#596]
After updating GoSublime, it fails to build MarGo. I could use Sublime Text with GoSublime and MarGo before the update. How can I get it to build successfully?

```
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/go/bin/go', 'build', '-v', '-x', '-o', 'gosublime.margo_r14.12.06-1_go1.2.exe', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr: `WORK=/var/folders/8y/qbx0vr3n5lq7skbdhktm27bc0000gn/T/go-build299424242
|                > runtime
|                > go build runtime: darwin/amd64 must be bootstrapped using make.bash`
|                > exception: `None`
|   install state: busy
| sublime.version: 3065
| sublime.channel: stable
|       about.ann: a14.02.25-1
|   about.version: r14.12.06-1
|         version: r14.12.06-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r14.12.06-1_go1.2.exe (missing)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.2
|          GOROOT: ~/Documents/Development/google-go-appengine-1.9.15/goroot
|          GOPATH: ~/Documents/Development/Go-Workspace
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
```

**Comment by ChristianSiegert** [comment]
I fixed it by downloading and installing Go 1.4.1, and setting `GOROOT` to "" (empty string) in `GoSublime.sublime-settings`.

**Comment by ChristianSiegert** [comment]
To make code completion work again, I had to do two things:
- Since I use the Google App Engine SDK for Go, I had to set `installsuffix`to `appengine` in `GoSublime.sublime-settings`.
- After MarGo was successfully built, I had to revert `GOROOT` from empty string to my previous setting. In my case this was `$HOME/Documents/Development/google-go-appengine-1.9.15/goroot`.

**Comment by vasureddym** [comment]
Thanks @ChristianSiegert your comments helped. except that I had to do it a little different in my case. 
Here is my scenario; I had go 1.4.2 installed, and sublime was configured and working well along with the auto-code-completion feature. Today I downloaded Appengine SDK (looks like AppEngine is using Go 1.4 per their documentation) and I was using sublime to write code, but the auto-complete wasn't pulling the code related to appengine specific packages which made sense because `GOROOT` was still pointing to previous go installation. However after I changed the `GOROOT` to point to the appengine's `goroot` folder, the MarGo build starting to fail, (like in your case). So here is what I did to fix it;

1. pointed the `GOROOT` back to the previous Go installation folder. verified that sublime code auto complete is working fine as it was.
2. opened the `GoSublime.sublime-settings` file, and did not find the `installsuffix` setting, so I added below code at the beginning of the settings file after the `{`
`"installsuffix": "appengine",`
3. changed the `GOROOT` environment variable to the `goroot` folder of the app engine SDK installation. 
4. closed sublime and reopened, tada, no marGo build error and also the code auto complete is working fine. 

thanks @ChristianSiegert for your post.
