### ISSUE TITLE
add errcheck?

### ISSUE THREAD

**Issue by yields** [DisposaBoy/GoSublime#615]
https://github.com/kisielk/errcheck

**Comment by albrow** [comment]
:+1: This would be a great addition! I haven't been able to find a plugin for errcheck that works.

**Comment by albrow** [comment]
@yields I just discovered that you can configure GoSublime to run errcheck (as well as other tools like go vet) on save. The errors show up as dots on the side and you can click on them to see a description.

See this article: http://www.wolfe.id.au/2015/03/05/using-sublime-text-for-go-development/

Since you can just configure GoSublime to do this I don't think it's necessary to add support out of the box.

My GoSublime.sublime-settings file looks like this now:

``` js
{
	// enable comp-lint, this will effectively disable the live linter
	"comp_lint_enabled": true,

	// list of commands to run
	"comp_lint_commands": [
	    // run errcheck on the package
	    {"cmd": ["errcheck"]},

	    // run go vet on the package
	    {"cmd": ["go", "vet"]},

	    // run `go install` on the package. GOBIN is set,
	    // so `main` packages shouldn't result in the installation of a binary
	    {"cmd": ["go", "install"]}
	],

	"on_save": [
	    // run comp-lint when you save,
	    // naturally, you can also bind this command `gs_comp_lint`
	    // to a key binding if you want
	    {"cmd": "gs_comp_lint"}
	],
}
```

**Comment by yields** [comment]
nice thanks @albrow!

**Comment by EugZol** [comment]
For it to ignore tests:

```
{"cmd": ["errcheck", "-ignoretests"]}
```
