### ISSUE TITLE
Cannot find the package in sublime text 3

### ISSUE THREAD

**Issue by yeasy** [DisposaBoy/GoSublime#628]
Following the installation instructions, but not find the package in the shown list.

Any suggestions?

Sublime Text Build 3083

Thanks!

**Comment by grange74** [comment]
Just tried it on a fresh install of ST3 build 3083 on OSX 10.10.3 and i was able to find GoSublime through the package control. Can you provide more info:
* do you have Package Control installed? if so can you see other plugins? 
* what OS are you running on?
* are you sure that GoSublime isn't already installed?

**Comment by yeasy** [comment]
Yes.
Windows7
Not installed.

I download the package manually into pkg dir, then can find the install. However, after the installation, it seems not work.

**Comment by grange74** [comment]
Sorry the problem is still not clear. Need more information in order to try to reproduce it.

> Following the installation instructions, but not find the package in the shown list.

Which installation instructions? the ones on the main [README.md](https://github.com/DisposaBoy/GoSublime#installation)?
What/where is the "shown list"? do you mean the menus?

> I download the package manually into pkg dir

Why aren't you using Package Control to download and install GoSublime?

> However, after the installation, it seems not work.

What doesn't work? syntax highlighting/code completing? what are you trying to do?

**Comment by yeasy** [comment]
The shown list is the package control installation list, can find the gosublime there after manually put the code under the pkg dir.
There is no highlighting and no completing.

So a guideline of manual installation would be of great help!
