### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by scottengle** [DisposaBoy/GoSublime#647]
There haven't been any commits from DisposaBoy since December, 2014 on any of their repos, and no pull requests processed on the GoSublime repo. I don't see an announcement in the repo's README, so I'm curious to know if this project has been abandoned. 

If abandoned, is there a leading active fork that I should be looking at?

**Comment by DisposaBoy** [comment]
I guess the best way to phrase it is: The project is in in *limbo*

* AFAICS, Sublime Text is abandonware
* ST2 doesn't quite perform as well as I'd like and ST3 just makes it worse
* This is mostly bitterness from years of this crap, but I've always thought the ST2 api/Py2K distro was kinda retarded. All I can say is that ST3/Py3K surely went full retard
* Any request for support is, AFAICT, simply ignored. I know this because requests to support@sublimetext.com *eventually* get a reply that directs you to sublimetext.com/forum/ where you'll find only fanboys and spam
* As I hear all the time: the license doesn't buy you support. Sublime Text is *unsupported* software
* etc.

**Comment by ORBAT** [comment]
As far as ST being abandoned goes, the last dev build at the time of writing [came out on July 10th](https://www.sublimetext.com/3dev). That said, there's a few forks of GoSublime that seem fairly active, with the one by @alexmullins [alexmullins/GoSublime](https://github.com/alexmullins/GoSublime) seemingly containing the most new work from other branches (based on a quick glance at the network.)

@DisposaBoy, it might be a good idea to think about giving other folks who are actively developing their forks of GoSublime write access to this repo: it's a damn good project, and I'd hate to see it languish in limbo.

**Comment by alexmullins** [comment]
@ORBAT  The fork I have currently does not work. I tried merging a few pull requests from the main repo, but haven't been able to track down the problems. I tried poking around the ST3 API and didn't get very far with it. 

Hey Disposa, if you don't mind me asking, are you still using Sublime Text for your Go development?

**Comment by liuhewei** [comment]
Sublime text is great. If it was really abandoned, feel sad for that... I haven't been using Gosublime plugin for a long time, now I'm using IntelliJ-IDEA with [Go plugin](https://plugins.jetbrains.com/plugin/5047), and it works well for me. It could be an option for your consideration @alexmullins. I'm still using ST3 as a code editor handling different languages and scripts, also Go codes sometimes as well. Intellij-IDEA is a very good IDE, which is not the purpose of ST3 in my opinion.

**Comment by DisposaBoy** [comment]
@alexmullins my setup hasn't changed (yet) although I'm still looking at possible alternative text editors

**Comment by liuhewei** [comment]
For someone who might care about, another project may be one substitute:  https://github.com/ironcladlou/GoTools

**Comment by nathany** [comment]
@DisposaBoy I've done my share of looking at alternative text editors as well, but I keep coming back to SublimeText 3 and GoSublime for the combination of features & performance.

Lately @wbond has done some work on https://github.com/golang/sublime-build which depends on https://github.com/golang/sublime-config. I didn't realize Package Control supports dependencies, which introduces some interesting possibilities. For example, it may be feasible to pull in SublimeLinter rather than building a linter UI? 

Maybe that would also reduce the burden of maintaining a large package that does everything.

**Comment by nathany** [comment]
Hi @DisposaBoy. Thanks for the gocode updates. It's also great to see the new Sublime Text forums and three significant Dev releases from @jskinner these past few days. Perhaps this issue can be closed? :wink:

**Comment by GoBijan** [comment]
"AFAICS, Sublime Text is abandonware"... Not anymore. JPS is back on track and is steadily pushing out new releases. wbond was also hired. great to see sublime advancing.

**Comment by marciol** [comment]
Go do Definition of Sublime Text plus the ctrlp fuzzy search of candidates plus fast preview make Sublime Text incomparable. This days I found a issue on fzf where someone asked for this kind of fast preview through fzf in vim.
