### ISSUE TITLE
GoSublime wrong indentation

### ISSUE THREAD

**Issue by danchenkov** [DisposaBoy/GoSublime#651]
I can't figure out why the following gets formatted this way (no unindent on closing curly brace) on re-indent (Edit-Line-Reindent). `go fmt` is definitely formatting it differently (and properly).

![image](https://cloud.githubusercontent.com/assets/161908/10121507/fa720698-64a3-11e5-9705-246b0c7d20ef.png)

UPDATE: The indentation (on save) result changes when `go` added of the `reindent_on_save` settings in the User Settings. Proper indentation occurs when `go` is not listed.

**Comment by DisposaBoy** [comment]
*workforme*&trade;

Does your use of the word `re-indent` mean the `Indentation: Reindent Lines` command? that's a Sublime Text builtin command that does something else. GoSublime's fmt should be enabled by default when you `save` the file or you can do it manually with the key binding <kbd>ctrl+. (dot)</kbd>,<kbd>ctrl+f</kbd>.

Otherwise post the code and instructions to reproduce the issue.
