### ISSUE TITLE
High CPU usage on non-Go code

### ISSUE THREAD

**Issue by lizrice** [DisposaBoy/GoSublime#653]
I'm fairly new to Golang and I had this plugin highly recommended. And it seems to be working fine when I'm working on Go code. But whenever I open anything non-Go (typically Python projects) I rapidly get 100%+ CPU usage - and this is new since I installed GoSublime. 

I'm sure this is nowhere near enough info to debug the problem, but I'm afraid I have no idea how to get logging (I'm using ST3). Let me know what info I could usefully collect and I'll very happily do so.

**Comment by DisposaBoy** [comment]
I can't imagine why that would happen. If there are any errors they would likely be printed in the Sublime Text console `menu: View > Show Console`.

* Is this something to do with the file content (non-utf8 encoding, etc.) or settings e.g. it's a `.py` file but for whatever reason it's using a `.go` syntax definition
* What's using 100% cpu (plugin_host, margo*.exe, etc.)?
* You can verify that it's GS my disabling all other plugins. If it continues then it's GS, otherwise it's likely a conflict with some other plugin or maybe you're using Package Control and it's installed multiple copies of GS
