### ISSUE TITLE
why can't I find gosublime from package control with option of install package?

### ISSUE THREAD

**Issue by igoing** [DisposaBoy/GoSublime#665]
when I search package control with sublime text3, I can not find gosublime from it. And I don't know why. What should I do? Thank you.
![notfound](https://cloud.githubusercontent.com/assets/11745892/12235565/8e44c842-b8af-11e5-8788-a78ce0e01ba6.jpg)

**Comment by yfanswer** [comment]
I also encountered this problem, and can you tell me how did you solve it?

**Comment by DisposaBoy** [comment]
@yfanswer see https://margo.sh/b/migrate/ for installation instructions

**Comment by ram-nadella** [comment]
@DisposaBoy thanks for the great plugin

Any particular reason for moving away from Package Control to a manual install process?

**Comment by DisposaBoy** [comment]
@ram-nadella a few reasons:

* PC, AFAIK, does automatic updates by default. This is very bad from a security POV IMO. It means anyone with access to the account of a plugin author, or the author themselves can silently push executable code onto your computer any time without you knowing. See also `Sidebar Enhancements-gate`.

* The above coupled with the fact that GS uses a rolling-release model and that users don't read anything meant that things can sometimes break while users are working. Imagine trying to make a deadline and then suddenly your tools break for unknown reasons.

* The result is that said (understandably) angry users direct their anger towards me.

* For those reasons GS hasn't support PC for years... which was fine because I'd just ignore PC-related issues.

* After years of receiving abuse for an underfunded project from people who didn't pay me to tolerate said abuse one PC user in particular decided to take it to the next level and at that point I decided to just stop sending updates to PC users altogether.

**Comment by dmitris** [comment]
would be great to have installation instructions in some GitHub pages - currently https://margo.sh/b/migrate/ does not open, I think github's uptime would be more reliable.
![image](https://user-images.githubusercontent.com/31205/57930082-57440500-78b5-11e9-8c0b-89022d6a00e4.png)

**Comment by greyhub** [comment]
Working for me.

## Add repository
1. Open Package Control Options 
Press `Ctrl + Shift + P`
1. Add the repository if its not exist
Type `Package Control: Add Repository`
1. A text box will appear at the bottom, paste the URL to the repository
Type `https://github.com/DisposaBoy/GoSublime`

## Add package
1. Open Package Control Options again 
Press `Ctrl + Shift + P`
1. Choose Install package
Type `Package Control: Install Package`
1. In the dialog box, type the name of your package
Type `GoSublime` and `Enter`

> `Wait` for installing and `restart` Sublime Text.

**Comment by estecaes** [comment]
Why @greyhub's comment is not  included as instruction on readme file?
