### ISSUE TITLE
MarGo build failed

### ISSUE THREAD

**Issue by mervin0502** [DisposaBoy/GoSublime#800]
Where is the `st/gui.GOROOT:` ?

> |    sh.bootstrap: 
|                > 	WARNING: GOROOT is different between your shell and ST/GUI environments
|                > 	     shell.GOROOT: /usr/lib/go
|                > 	    st/gui.GOROOT: /opt/go
|                > 	using shell env GOPATH=~/Work/05Code/Go
|                > 	using shell env GOROOT=/usr/lib/go
|                > 	using shell env PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
|                > 	go version: `go1.9.2` (raw version string `go1.9.2`)
|                > 	shell bootstrap took 0.248s
|                >

**Comment by DisposaBoy** [comment]
Do you mean where it's being set? probably in some startup files like `/etc/*bash*` or `/etc/environment`... maybe you have another installation of Go on your system.

**Comment by mervin0502** [comment]
In my os, `echo $GOROOT` is `/usr/lib/go`

**Comment by DisposaBoy** [comment]
It says that because you're running that command in your shell (e.g. bash). But GOROOT is also being set earlier during boot/login, so when you run GUI programs like ST, they see the value that was set at boot/login, not the one being set in your shell.

Assuming your shell is bash try the following commands to see what each shell has for your GOROOT

    env GOROOT= sh -c 'echo sh: $GOROOT
    env GOROOT= bash -c 'echo bash: $GOROOT

Open the ST console <kbd>ctrl+`</kbd> and run the command `import os; os.environ.get('GOROOT')` to see what ST sees.

**Comment by mervin0502** [comment]
Thank you for your help. I have resolved it.
