### ISSUE TITLE
Error in GoSublime post save

### ISSUE THREAD

**Issue by dbeckwith** [DisposaBoy/GoSublime#808]
I have my settings set up to run `goimports` on save:
```
{
    "fmt_cmd": ["goimports", "-e"]
}
```
But it's not working, and I see this in the console:
```
Traceback (most recent call last):
  File "/home/dbeckwith/.config/sublime-text-3/Packages/GoSublime/gsev.py", line 14, in <lambda>
    sublime.set_timeout(lambda: do_post_save(view), 0)
  File "/home/dbeckwith/.config/sublime-text-3/Packages/GoSublime/gsev.py", line 49, in do_post_save
    cmd = c.get('cmd', '')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by dbeckwith** [comment]
Also the `GoSublime: Fmt and Save` does nothing?

**Comment by DisposaBoy** [comment]
It looks like your `on_save` setting might be wrong. It's supposed to be a list of objects, but the exception suggests you have at least one string in there.

**Comment by dbeckwith** [comment]
Ah, okay that was a problem, but still the `Fmt and Save` command does nothing for me, and it won't format on save. I don't see any logs when I save or when I run the command through the search. The file definitely has formatting problems, and running `goimports` manually shows changes.

**Comment by DisposaBoy** [comment]
What does the rest of your settings look like?

The only way I can reproduce this is if I enable the new version of margo fully and I didn't share any info on how to do it so I doubt you did that - unless you accidentally pressed <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>

**Comment by dbeckwith** [comment]
I gave the entirety of my GoSublime settings above. I think it was working last week even, I'm not sure what changed. Any suggestions of logs or something I could look at to debug it?

**Comment by DisposaBoy** [comment]
There was a big update last week, but apart from the <kbd>ctrl+.</kbd>,<kbd>ctrl+f</kbd> key binding not much related code should've changed.

My simplest suggestions would be to:

* downgrade to the previous version

* upgrade to the new margo binary instead:
  * press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> to open the extension file which is a copy of https://github.com/DisposaBoy/GoSublime/blob/master/src/disposa.blue/margo/extension-example/extension-example.go
  * you can comment out `golang.GoFmt,` and un-comment `// golang.GoImports,` to use goimports instead of gofmt
  * you can also comment out `DayTimeStatus,` if you don't want the time to appear in the status bar
  * save the file and then restart Sublime Text

**Comment by dbeckwith** [comment]
Thanks I'll try those out and get back to you.

**Comment by dbeckwith** [comment]
I think I just hadn't restarted Sublime in a while (like a week), and updating the extension without restarting was causing the issue. I restarted Sublime and it works now.
