### ISSUE TITLE
I don`t want gotest my code when I save

### ISSUE THREAD

**Issue by kfrico** [DisposaBoy/GoSublime#835]
I don`t want gotest my code when I save.
could you tell me how to setting it that do not gotest my code when I save file
Thank you

**Comment by kortschak** [comment]
This really should not be on by default.

**Comment by DisposaBoy** [comment]
@kortschak looking at the old config https://github.com/DisposaBoy/GoSublime/blob/master/GoSublime.sublime-settings, I don't see anything that runs `go test`. For the new version of margo, nothing is enabled unless you press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> which opens the `margo.go` (and why wouldn't you read what's in it?).

**Comment by kortschak** [comment]
Yeah, that's why I'm commenting here. I'm working on something that has tests, but I'm messing with the implementation in very nasty ways that break the tests in ways that result in very large memory allocations - I knew this and was not running tests for a reason temporarily. I noticed that the machine was becoming sluggish and then say the test executable running. Killing it resulted in repeated respawning and I tracked this down to being due to margo. I looked in the GoSublime settings files (default and user) that you link to and saw no indication of anything that would cause tests to be run on save - as is the case in the commited file, I see `"on_save": []`. So more googling and I find this issue, comment out the offending line that runs tests with race detection on and now everyone is happy. Note that I have not ever done <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> prior to seeing the instructions [above](https://github.com/DisposaBoy/GoSublime/issues/835#issuecomment-391066414).

I didn't read what's in the config because I did not expect to need to. I've been using GoSublime for a few years and the last time I read the CHANGELOG (I'm on 2feba14a18576f203ad92c301055abb7bb00daa2), it says that the new version is close to being ready. So given that, and that is only says "If you'd like to test it out, press `ctrl+.`,`ctrl+x` or `cmd+.`,`cmd+x`
to open the extension file and then save it and restart sublime text" and I didn't want to. I could leave it alone. Was I wrong?
