### ISSUE TITLE
margo.sh links in warning for go1.11 do not work (subject to internet block provider filter)

### ISSUE THREAD

**Issue by kortschak** [DisposaBoy/GoSublime#848]
This is a note rather than an issue that you need to deal with.

I'm running a go devel version, so I see the migration warning on start up. This gives a link to https://margo.sh/b/migrate/?_r=gs. Following this link give a connection failure warning.

```
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

Falling back to http on the basis that that might work I get an $EMPLOYER site blacklist warning.
```
The web page requested was:

http://margo.sh/b/migrate/?_r=gs

The web page was categorised under:

adult

If you believe that the page is incorrectly categorised, and should be freely accessible, click the Recategorisation button.
```

I've checked access and content via my mobile ISP and don't get the https fault or see anything that would justify the block.

I have filed a recategorisation request. So hopefully this will be rectified. (Note that $EMPLOYER uses a third party filter provider, https://www.paloaltonetworks.com/, so this may affect others).

**Comment by kortschak** [comment]
PA networks have reclassified this and now both links work without failure.

**Comment by DisposaBoy** [comment]
Thanks for sorting that out. 

I assume you can access https://kuroku.io / https://git.kuroku.io just fine?

I can only imagine that it's the name `margo` or `.sh` that caused it. The servers do share their spare resources with the Tor network, but user requests go through Cloudflare  so that  shouldn't be a problem (I hope).

I've arranged to have https://margo.sh mirrored at https://margo.kuroku.io at least until I can investigate more.
