### ISSUE TITLE
reloading go.mod

### ISSUE THREAD

**Issue by Elojah** [DisposaBoy/GoSublime#942]
Hello DIsposaBoy,

My team and I moved to go modules recently and i have an issue with `GoSublime`.
`go.mod` file is constantly updated 

console:
```
reloading /pathtoproject/go.mod
reloading /pathtoproject/go.mod
reloading /pathtoproject/go.mod
reloading /pathtoproject/go.mod
reloading /pathtoproject/go.mod
```

Happens like twice+ per second, and `go.mod` may be impossible to edit because constantly updated.

Looks like this line `	google.golang.org/appengine v1.4.0 // indirect` is constantly added and removed, but still, why run a go build so many times ?

This reloading stops when i restart margo so i guess this is where issue come from.

Do you have any clue on this issue ? How may i give you more accurate informations on this ?

Thanks for your work

**Comment by DisposaBoy** [comment]
Have you tried to `next` branch? before that there is no support for Go modules. We also use the `go/build` package which might call the `go` command which likely results in crazy side-effects like updating `go.mod`.

**Comment by Elojah** [comment]
I tried on `next` branch and `go.mod` keep reloading but on save only which may be more or less expected (why go.mod content change is probably independent of this plugin).

Can i expect `next` branch to be stable ?

So it can be closed, thanks for your assist

**Comment by DisposaBoy** [comment]
> I tried on `next` branch and `go.mod` keep reloading but on save only which may be more or less expected (why go.mod content change is probably independent of this plugin).

That's probably triggered by a linter like the `golang.GoInstallDiscardBinaries` or `golang.GoInstall` reducers. (untested) You can probably work around it by setting `GOFLAGS=-mod=readonly` globally or as an argument to the linter e.g. `golang.GoInstall("-mod=readonly")`.

This issue is being tracked at https://github.com/KurokuLabs/margo/issues/110.

> Can i expect `next` branch to be stable ?

It's stable in the sense that it's what's coming _next_ and I only push there once I feel like the code can go to `development` but is lacking testing.
